AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ApiName:
    Type: String
    Default: openbrighton-main-api-gateway
    Description: The name of the HTTP API

  StageName:
    Type: String
    Default: v1
    Description: The name of the stage

  DomainName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /openbrighton/main/domain
    Description: The custom domain name for the API

  HostedZoneId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /openbrighton/main/hosted-zone/id
    Description: The ID of the Route 53 hosted zone

  SSMNamespace:
    Type: String
    Default: /openbrighton/main
    Description: The namespace for the SSM parameters

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: !Ref StageName
      AutoDeploy: true

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "api.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "api.${DomainName}"
          HostedZoneId: !Ref HostedZoneId

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Sub "api.${DomainName}"
      DomainNameConfigurations:
        - CertificateArn: !Ref Certificate
          EndpointType: REGIONAL

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref ApiDomainName
      Stage: !Ref StageName
      ApiMappingKey: "" # Empty = maps to root "/"

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "api.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId

  ApiGatewayIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join
        - ""
        - - !Ref SSMNamespace
          - "/api-gateway/id"
      Type: String
      Value: !Ref HttpApi